export type {
  ConfigPatch,
  KbDesktopRpcSchema,
  ListOpts,
  ListStats,
  OpenDialogOpts,
  PreviewImageResult,
  RpcCallParams,
  RpcCallResponse,
  RpcDbStats,
  RpcGetConfigPayload,
  RpcImportResult,
  RpcKnowledge,
  RpcListEntry,
  RpcSyncFileResult,
  RpcSyncProgressPayload,
  TaskCreateInput,
  TaskUpdateInput,
  TaskView
} from './kb_rpc_schema'
